Configuratron:
  use_only:
    - mmidb
    - bci_iv_2a
    - ern
    - erpbci
    - sleep-edf
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: models/encoder.pt
context_weights: models/contextualizer.pt

datasets: !include configs/downstream_datasets.yml

